# local 개발용 docker compose file
services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    env_file:
      - .env.local
    container_name: keepintouch-server
    restart: always
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      postgres:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
  pgadmin_data:
