name: Build and Push Docker Image
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: keepintouch/keepintouch-be:release-v2

    - name: Connect to Server & Execute Application
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DEV_BE_HOST }}
        username: ${{ secrets.DEV_BE_USERNAME }}
        key: ${{ secrets.DEV_BE_SSH_KEY }}
        port: 22
        script: |
          sudo docker stop keepintouch-be-v2
          sudo docker rm   keepintouch-be-v2
          sudo docker rmi  ${{ secrets.DOCKERHUB_USERNAME }}/keepintouch-be:release-v2
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/keepintouch-be:release-v2
          sudo docker run -d -m 200m --env-file ${{secrets.DEV_BE_ENV_WD}}  --memory-swap 1024m --restart always --name keepintouch-be-v2 -p 8000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/keepintouch-be:release-v2
